language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
  - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake -qt=qt5 StaircaseCardCreatorConsole.pro
  - make debug
  - ./StaircaseCardCreatorConsole
  # Desktop
  - qmake -qt=qt5 StaircaseCardCreatorDesktop.pro
  - make debug
  - ./StaircaseCardCreatorDesktop &
  - sleep 10
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)